spring:
  mail:
    host: smtp.gmail.com
    username: atulpatel2001a@gmail.com
    password: uqbkjpmwrrqtyxhc
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

